/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.ChiTietLoaiGheBUS;
import DTO.ChiTietLoaiGheDTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class ChiTietLoaiGheGUI extends javax.swing.JDialog {

    private DefaultTableModel model;
    private String xoaChiTietLoaiGhe;
    public String maloaighe;
    /**
     * Creates new form MayBayGUI
     */
    public ChiTietLoaiGheGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public String getContent()
    {
        return txtMaLoaiGhe.getText();
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLoaiGhe = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLoaiGhe = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaChuyen = new javax.swing.JTextField();
        txtGiaVe = new javax.swing.JTextField();
        btAddLoaiGhe = new javax.swing.JButton();
        btEditLoaiGhe = new javax.swing.JButton();
        btDeleteLoaiGhe = new javax.swing.JButton();
        btResetLoaiGhe = new javax.swing.JButton();
        btChonLoaiGhe = new javax.swing.JButton();
        btMaChuyen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chi Tiết Loại Ghế");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tblDSLoaiGhe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Loại Ghế", "Mã Chuyến ", "Tên Loại ", "Giá Vé"
            }
        ));
        tblDSLoaiGhe.setRowHeight(30);
        tblDSLoaiGhe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSLoaiGheMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSLoaiGhe);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Loại Ghế:");

        jLabel3.setText("Tên Loại:");

        jLabel4.setText("Mã Chuyến:");

        jLabel5.setText("Giá Vé:");

        txtMaChuyen.setEditable(false);

        btAddLoaiGhe.setText("Thêm");
        btAddLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLoaiGheActionPerformed(evt);
            }
        });

        btEditLoaiGhe.setText("Sửa");
        btEditLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditLoaiGheActionPerformed(evt);
            }
        });

        btDeleteLoaiGhe.setText("Xóa");
        btDeleteLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteLoaiGheActionPerformed(evt);
            }
        });

        btResetLoaiGhe.setText("Reset");
        btResetLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetLoaiGheActionPerformed(evt);
            }
        });

        btChonLoaiGhe.setText("CHỌN");
        btChonLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonLoaiGheActionPerformed(evt);
            }
        });

        btMaChuyen.setText("Chọn");
        btMaChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaChuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btAddLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDeleteLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btResetLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btChonLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(txtGiaVe))
                        .addGap(18, 18, 18)
                        .addComponent(btMaChuyen)
                        .addGap(67, 67, 67))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMaChuyen))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtGiaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddLoaiGhe, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btEditLoaiGhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDeleteLoaiGhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btChonLoaiGhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btResetLoaiGhe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ChiTietLoaiGheBUS bus = new ChiTietLoaiGheBUS();
        if (ChiTietLoaiGheBUS.dsTable == null) {
            bus.docDSTable();
        }
        Vector header = new Vector();
        header.add("Mã Loại Ghế");
        header.add("Mã Chuyến");
        header.add("Tên Loại");
        header.add("Giá Vé");
        model = new DefaultTableModel(header, 0);
        for (ChiTietLoaiGheDTO tb : ChiTietLoaiGheBUS.dsTable) {
            Vector row = new Vector();
            row.add(tb.MaLoaiGhe);
            row.add(tb.MaChuyen);
            row.add(tb.TenLoai);
            row.add(tb.GiaVe);
            model.addRow(row);
        }
        tblDSLoaiGhe.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    private void tblDSLoaiGheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSLoaiGheMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSLoaiGhe.getModel();
        int i = tblDSLoaiGhe.getSelectedRow();
        if (i >= 0) {
            xoaChiTietLoaiGhe = tblDSLoaiGhe.getValueAt(i, 0).toString();
            ChiTietLoaiGheDTO ctlg = new ChiTietLoaiGheDTO();
            ctlg = ChiTietLoaiGheBUS.dsTable.get(i);
            txtMaLoaiGhe.setText(ctlg.getMaLoaiGhe());
            txtMaChuyen.setText(ctlg.getMaChuyen());
            txtTenLoai.setText(ctlg.getTenLoai());
            txtGiaVe.setText(String.valueOf(ctlg.getGiaVe()));
            
        }
    }//GEN-LAST:event_tblDSLoaiGheMouseClicked

    private void btAddLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLoaiGheActionPerformed
        // TODO add your handling code here:
        ChiTietLoaiGheDTO ctlg = new ChiTietLoaiGheDTO();
        ctlg.MaLoaiGhe = txtMaLoaiGhe.getText();
        ctlg.MaChuyen = txtMaChuyen.getText();
        ctlg.TenLoai = txtTenLoai.getText();
        ctlg.GiaVe = Integer.parseInt(txtGiaVe.getText());
        ChiTietLoaiGheBUS bus = new ChiTietLoaiGheBUS();
        bus.them(ctlg);
        Vector row = new Vector();
        row.add(ctlg.MaLoaiGhe);
        row.add(ctlg.MaChuyen);
        row.add(ctlg.TenLoai);
        row.add(ctlg.GiaVe);
        model.addRow(row);
        tblDSLoaiGhe.setModel(model);
    }//GEN-LAST:event_btAddLoaiGheActionPerformed

    private void btEditLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditLoaiGheActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSLoaiGhe.getModel();
        int i = tblDSLoaiGhe.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        }
        ChiTietLoaiGheDTO ctlg = new ChiTietLoaiGheDTO();
        ctlg.MaLoaiGhe = txtMaLoaiGhe.getText();
        ctlg.MaChuyen = txtMaChuyen.getText();
        ctlg.TenLoai = txtTenLoai.getText();
        ctlg.GiaVe =  Integer.parseInt(txtGiaVe.getText());
        ChiTietLoaiGheBUS bus = new ChiTietLoaiGheBUS();
        bus.sua(ctlg);
        
        tblDSLoaiGhe.setModel(model);
        model.setValueAt(ctlg.MaLoaiGhe, i, 0);
        model.setValueAt(ctlg.MaChuyen, i, 1);
        model.setValueAt(ctlg.TenLoai, i, 2);
        model.setValueAt(ctlg.GiaVe, i, 3);
        bus.docDSTable();
    }//GEN-LAST:event_btEditLoaiGheActionPerformed

    private void btDeleteLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteLoaiGheActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSLoaiGhe.getModel();

        int i = tblDSLoaiGhe.getSelectedRow();
                if(i<0)
                 {
                     JOptionPane.showMessageDialog(null,"Bạn cần chọn dòng để xóa");
                 }
                else{
                      int chon = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không","Xóa sách",JOptionPane.YES_NO_OPTION);
                      if(chon == JOptionPane.YES_OPTION){
                            ChiTietLoaiGheDTO ctlg = new ChiTietLoaiGheDTO();
                            ctlg = ChiTietLoaiGheBUS.dsTable.remove(i);
                            ChiTietLoaiGheBUS bus = new ChiTietLoaiGheBUS();
                            if (i >= 0) {
                            xoaChiTietLoaiGhe = tblDSLoaiGhe.getValueAt(i, 0).toString();
                            }
                            bus.xoa(xoaChiTietLoaiGhe);
                            model.removeRow(i);
                            tblDSLoaiGhe.setModel(model);
                      }
                }
    }//GEN-LAST:event_btDeleteLoaiGheActionPerformed

    private void btResetLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetLoaiGheActionPerformed
        // TODO add your handling code here:
        txtMaLoaiGhe.setText("");
         txtMaChuyen.setText("");
        txtTenLoai.setText("");
        txtGiaVe.setText("");
    }//GEN-LAST:event_btResetLoaiGheActionPerformed

    private void btMaChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaChuyenActionPerformed
        // TODO add your handling code here:
        ChuyenBayV2GUI1 dialog = new ChuyenBayV2GUI1( null, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
        txtMaChuyen.setText(temp);
    }//GEN-LAST:event_btMaChuyenActionPerformed

    private void btChonLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonLoaiGheActionPerformed
        // TODO add your handling code here:
        int i = tblDSLoaiGhe.getSelectedRow();
            if(i>=0)
            {
                ChiTietLoaiGheDTO ctlg = new ChiTietLoaiGheDTO();
                ChiTietLoaiGheBUS bus = new ChiTietLoaiGheBUS();
                if(ChiTietLoaiGheBUS.dsTable == null) bus.docDSTable();
                ctlg = bus.dsTable.get(i);
                maloaighe = ctlg.getMaLoaiGhe();
                VeMayBayGUI.txtMaLoaiGhe.setText(maloaighe);
                VeMayBayGUI.txtMaLoaiGhe.setEditable(false);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng trên bảng");
            }
    }//GEN-LAST:event_btChonLoaiGheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoaiGheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoaiGheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoaiGheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietLoaiGheGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChiTietLoaiGheGUI dialog = new ChiTietLoaiGheGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLoaiGhe;
    private javax.swing.JButton btChonLoaiGhe;
    private javax.swing.JButton btDeleteLoaiGhe;
    private javax.swing.JButton btEditLoaiGhe;
    private javax.swing.JButton btMaChuyen;
    private javax.swing.JButton btResetLoaiGhe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSLoaiGhe;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtMaChuyen;
    private javax.swing.JTextField txtMaLoaiGhe;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
