/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChuyenBayBUS;
import BUS.Excel;
import static BUS.Excel.readExcel;
import DTO.ChuyenBayDTO;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dell
 */
public class ChuyenBayGUI extends javax.swing.JFrame {

    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");

    private DefaultTableModel model;
    private String xoaCB;

    /**
     * Creates new form ChuyenBayGUI
     */
    public ChuyenBayGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaChuyen = new javax.swing.JTextField();
        txtMaLoTrinh = new javax.swing.JTextField();
        txtMaMB = new javax.swing.JTextField();
        btLoTrinh = new javax.swing.JButton();
        btMayBay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTGDi = new com.github.lgooddatepicker.components.TimePicker();
        txtTGDen = new com.github.lgooddatepicker.components.TimePicker();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        intSoGheDB = new javax.swing.JTextField();
        intSoGheVIPDB = new javax.swing.JTextField();
        btAddChuyenBay = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        tkDate1 = new com.toedter.calendar.JDateChooser();
        tkDate2 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btTimKiem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        txtNgayDi = new com.toedter.calendar.JDateChooser();
        txtNgayDen = new com.toedter.calendar.JDateChooser();
        btDocExcel = new javax.swing.JButton();
        btXuatExcel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSCB = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\plane.png")); // NOI18N
        jLabel11.setText("QUẢN LÝ BÁN VÉ MÁY BAY");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CHUYẾN BAY");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Chuyến:");

        jLabel3.setText("Mã Lộ Trình:");

        jLabel4.setText("Mã Máy Bay:");

        txtMaLoTrinh.setEditable(false);

        txtMaMB.setEditable(false);

        btLoTrinh.setText("...");
        btLoTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoTrinhActionPerformed(evt);
            }
        });

        btMayBay.setText("...");
        btMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMayBayActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày Đi:");

        jLabel6.setText("Giờ Đi:");

        jLabel7.setText("Ngày Đến:");

        jLabel8.setText("Giờ Đến:");

        jLabel9.setText("Số Ghế Hiện Có:");

        jLabel10.setText("Số Ghế VIP hiện có:");

        btAddChuyenBay.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\save.png")); // NOI18N
        btAddChuyenBay.setText("Thêm");
        btAddChuyenBay.setBackground(new java.awt.Color(0, 255, 0));
        btAddChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddChuyenBayMouseClicked(evt);
            }
        });

        btSua.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\edit.png")); // NOI18N
        btSua.setText("Sửa");
        btSua.setBackground(new java.awt.Color(0, 255, 255));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btReset.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\reset.png")); // NOI18N
        btReset.setText("Reset");
        btReset.setBackground(new java.awt.Color(240, 252, 0));
        btReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btResetMouseClicked(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel12.setText("Đến:");

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        tkDate1.setDateFormatString("yyyy-MM-dd");

        tkDate2.setDateFormatString("yyyy-MM-dd");

        jLabel13.setText("Ngày Đi: Từ");

        jLabel14.setText("Mã Chuyến");

        btTimKiem.setText("Tìm kiếm");
        btTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTimKiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tkDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tkDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTimKiem)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tkDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tkDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(btTimKiem))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\delete.png")); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setBackground(new java.awt.Color(255, 0, 0));
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXoaMouseClicked(evt);
            }
        });

        txtNgayDi.setDateFormatString("yyyy-MM-dd");

        txtNgayDen.setDateFormatString("yyyy-MM-dd");

        btDocExcel.setText("Đọc EXCEL");
        btDocExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDocExcelMouseClicked(evt);
            }
        });

        btXuatExcel.setText("Xuất EXCEL");
        btXuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXuatExcelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLoTrinh))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(txtMaMB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btMayBay))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btAddChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(intSoGheDB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTGDi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtNgayDen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtTGDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intSoGheVIPDB, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDocExcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoTrinh)
                    .addComponent(jLabel6)
                    .addComponent(txtTGDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTGDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMayBay)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(intSoGheDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intSoGheVIPDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btDocExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btAddChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXuatExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDSCB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chuyến", "Mã Lộ Trình", "Mã Máy Bay", "Ngày Đi", "Ngày Đến", "Giờ Đi", "Giờ Đến", "Số Ghế Còn Lại", "Số Ghế VIP Còn Lại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSCB.setPreferredSize(new java.awt.Dimension(300, 200));
        tblDSCB.setRowHeight(30);
        tblDSCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSCBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSCB);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ChuyenBayBUS bus = new ChuyenBayBUS();
        if (ChuyenBayBUS.dscb == null) {
            bus.docDSCB();
        }
        Vector header = new Vector();
        header.add("Mã Chuyến");
        header.add("Mã Lộ Trình");
        header.add("Mã Máy Bay");
        header.add("Ngày Đi");
        header.add("Ngày Đến");
        header.add("T.Gian Đi");
        header.add("T.Gian Đến");
        header.add("S.Ghế đã bán");
        header.add("S.Ghế VIP đã bán");
        model = new DefaultTableModel(header, 0);
        ChuyenBayBUS.dscb.stream().map((cb) -> {
            Vector row = new Vector();
            row.add(cb.MaChuyen);
            row.add(cb.MaLoTrinh);
            row.add(cb.MaMB);
            row.add(cb.NgayDi);
            row.add(cb.NgayDen);
            row.add(cb.TGDi);
            row.add(cb.TGDen);
            row.add(cb.SoGheDB);
            row.add(cb.SoGheVIPDB);
            return row;
        }).forEachOrdered((row) -> {
            model.addRow(row);
        });
        tblDSCB.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    private void btAddChuyenBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddChuyenBayMouseClicked
        // TODO add your handling code here:
        if("".equals(txtMaChuyen.getText()) || "".equals(txtMaLoTrinh.getText()) ||
                          "".equals(txtMaMB.getText()) || "".equals(txtNgayDi.getDate())
                                  || "".equals(txtNgayDen.getDate()) ||
                          "".equals(txtTGDi.getText()) || "".equals(txtTGDen.getText())||"".equals(intSoGheDB.getText())||"".equals(intSoGheVIPDB.getText())){
                    JOptionPane.showMessageDialog(null,"Mời bạn nhập đầy đủ thông tin !!!");
                }
        else if ((txtNgayDi.getDate()).before(txtNgayDen.getDate())){
        ChuyenBayDTO cb = new ChuyenBayDTO();
        cb.MaChuyen = txtMaChuyen.getText();
        cb.MaLoTrinh = txtMaLoTrinh.getText();
        cb.MaMB = txtMaMB.getText();
        cb.NgayDi = df.format(txtNgayDi.getDate());
        cb.NgayDen = df.format(txtNgayDen.getDate());
        cb.TGDi = txtTGDi.getText();
        cb.TGDen = txtTGDen.getText();
        cb.SoGheDB = Integer.parseInt(intSoGheDB.getText());
        cb.SoGheVIPDB = Integer.parseInt(intSoGheVIPDB.getText());
        ChuyenBayBUS bus = new ChuyenBayBUS();
        bus.them(cb);
        Vector row = new Vector();
        row.add(cb.MaChuyen);
        row.add(cb.MaLoTrinh);
        row.add(cb.MaMB);
        row.add(cb.NgayDi);
        row.add(cb.NgayDen);
        row.add(cb.TGDi);
        row.add(cb.TGDen);
        row.add(cb.SoGheDB);
        row.add(cb.SoGheVIPDB);
        model.addRow(row);
        tblDSCB.setModel(model);
    }//GEN-LAST:event_btAddChuyenBayMouseClicked
    }
    private void btLoTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoTrinhActionPerformed
        // TODO add your handling code here:
        LoTrinhGUI dialog = new LoTrinhGUI(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
            txtMaLoTrinh.setText(temp);    
    }//GEN-LAST:event_btLoTrinhActionPerformed

    private void btMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMayBayActionPerformed
        // TODO add your handling code here:
        MayBayGUI dialog = new MayBayGUI(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
        txtMaMB.setText(temp);
    }//GEN-LAST:event_btMayBayActionPerformed

    private void tblDSCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSCBMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSCB.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int i = tblDSCB.getSelectedRow();
        if (i >= 0) {
            xoaCB = tblDSCB.getValueAt(i, 0).toString();
            ChuyenBayDTO chuyenbay = new ChuyenBayDTO();
            chuyenbay = ChuyenBayBUS.dscb.get(i);
            txtMaChuyen.setText(chuyenbay.getMaChuyen());
            txtMaLoTrinh.setText(chuyenbay.getMaLoTrinh());
            txtMaMB.setText(chuyenbay.getMaMB());
            try {
                txtNgayDi.setDate(sdf.parse(chuyenbay.getNgayDi()));
            } catch (ParseException ex) {
                Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                txtNgayDen.setDate(sdf.parse(chuyenbay.getNgayDen()));
            } catch (ParseException ex) {
                Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtTGDi.setText(chuyenbay.getTGDi());
            txtTGDen.setText(chuyenbay.getTGDen());
            intSoGheDB.setText(String.valueOf(chuyenbay.getSoGheDB()));
            intSoGheVIPDB.setText(String.valueOf(chuyenbay.getSoGheVIPDB()));
        }
    }//GEN-LAST:event_tblDSCBMouseClicked

    private void btXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSCB.getModel();

        int i = tblDSCB.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để xóa");
        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa sách", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                ChuyenBayDTO cb = new ChuyenBayDTO();
                cb = ChuyenBayBUS.dscb.remove(i);
                ChuyenBayBUS bus = new ChuyenBayBUS();
                if (i >= 0) {
                    xoaCB = tblDSCB.getValueAt(i, 0).toString();
                }
                bus.xoa(xoaCB);
                model.removeRow(i);
                tblDSCB.setModel(model);
            }
        }
    }//GEN-LAST:event_btXoaMouseClicked

    private void btResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResetMouseClicked
        // TODO add your handling code here:
        txtMaChuyen.setText("");
        txtMaMB.setText("");
        txtMaLoTrinh.setText("");
        txtNgayDi.setDate(null);
        txtNgayDen.setDate(null);
        txtTGDi.setText("");
        txtTGDen.setText("");
        intSoGheDB.setText(null);
        intSoGheVIPDB.setText(null);
    }//GEN-LAST:event_btResetMouseClicked

    private void btTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTimKiemMouseClicked
        // TODO add your handling code here:
        ChuyenBayBUS bus = new ChuyenBayBUS();

        ArrayList<ChuyenBayDTO> list = null;
        try {
            list = bus.timkiemNC(tkDate1.getDate(), tkDate2.getDate());
        } catch (ParseException ex) {
            Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        model.setRowCount(0);
        revalidate();
        for (ChuyenBayDTO i : list) {
            Vector row = new Vector();
            row.add(i.getMaChuyen());
            row.add(i.getMaLoTrinh());
            row.add(i.getMaMB());
            row.add(i.getNgayDi());
            row.add(i.getNgayDen());
            row.add(i.getTGDi());
            row.add(i.getTGDen());
            row.add(i.getSoGheDB());
            row.add(i.getSoGheVIPDB());
            model.addRow(row);
        }

    }//GEN-LAST:event_btTimKiemMouseClicked

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSCB.getModel();
        int i = tblDSCB.getSelectedRow();
        String MaChuyen = txtMaChuyen.getText();
        int check = 0;
        for (ChuyenBayDTO x : ChuyenBayBUS.dscb) {
            if (x.getMaChuyen().equals(txtMaChuyen.getText())) {
                check = 1;
            }
        }
        ChuyenBayBUS.dscb.stream().filter((x) -> (x.getMaChuyen().equals(MaChuyen)));
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        } else if (check == 0) {
            JOptionPane.showMessageDialog(null, "Mã chuyến bay không được sửa");
            txtMaChuyen.requestFocus();

        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không", "Sửa", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION && check == 1) {

                ChuyenBayDTO cb = new ChuyenBayDTO();
                cb.MaChuyen = txtMaChuyen.getText();
                cb.MaLoTrinh = txtMaLoTrinh.getText();
                cb.MaMB = txtMaMB.getText();
                cb.NgayDi = df.format(txtNgayDi.getDate());
                cb.NgayDen = df.format(txtNgayDen.getDate());
                cb.TGDi = txtTGDi.getText();
                cb.TGDen = txtTGDen.getText();
                cb.SoGheDB = Integer.parseInt(intSoGheDB.getText());
                cb.SoGheVIPDB = Integer.parseInt(intSoGheVIPDB.getText());
                ChuyenBayBUS bus = new ChuyenBayBUS();
                bus.sua(cb);
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Vector row = new Vector();
                row.add(cb.MaChuyen);
                row.add(cb.MaLoTrinh);
                row.add(cb.MaMB);
                row.add(cb.NgayDi);
                row.add(cb.NgayDen);
                row.add(cb.TGDi);
                row.add(cb.TGDen);
                row.add(cb.SoGheDB);
                row.add(cb.SoGheVIPDB);
                model.addRow(row);
                tblDSCB.setModel(model);
                model.setValueAt(cb.MaChuyen, i, 0);
                model.setValueAt(cb.MaLoTrinh, i, 1);
                model.setValueAt(cb.MaMB, i, 2);
                model.setValueAt(cb.NgayDi, i, 3);
                model.setValueAt(cb.NgayDen, i, 4);
                model.setValueAt(cb.TGDi, i, 5);
                model.setValueAt(cb.TGDen, i, 6);
                model.setValueAt(cb.SoGheDB, i, 7);
                model.setValueAt(cb.SoGheVIPDB, i, 8);
                bus.docDSCB();
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btDocExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDocExcelMouseClicked
        // TODO add your handling code here:
        try {
                    tblDSCB.setModel(readExcel("C:/Zreport/ChuyenBay.xls"));
                } catch (IOException ex) {
                    Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
        JOptionPane.showMessageDialog(null, "Đọc file excel thành công!");
    }//GEN-LAST:event_btDocExcelMouseClicked

    private void btXuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXuatExcelMouseClicked
        // TODO add your handling code here:
        Excel ex = new Excel();
        try {
            ex.writeExcel(tblDSCB,"C:/Zreport/ChuyenBay.xls");
        } catch (IOException ex1) {
            Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex1);
        }
        JOptionPane.showMessageDialog(null, "Xuất file excel thành công!");
    }//GEN-LAST:event_btXuatExcelMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        ChuyenBayBUS bus = new ChuyenBayBUS();

        ArrayList<ChuyenBayDTO> list = null;
        try {
            list = bus.timKiem(txtTimKiem.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        model.setRowCount(0);
        revalidate();
        for (ChuyenBayDTO i : list) {
            Vector row = new Vector();
            row.add(i.getMaChuyen());
            row.add(i.getMaLoTrinh());
            row.add(i.getMaMB());
            row.add(i.getNgayDi());
            row.add(i.getNgayDen());
            row.add(i.getTGDi());
            row.add(i.getTGDen());
            row.add(i.getSoGheDB());
            row.add(i.getSoGheVIPDB());
            model.addRow(row);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenBayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChuyenBayGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddChuyenBay;
    private javax.swing.JButton btDocExcel;
    private javax.swing.JButton btLoTrinh;
    private javax.swing.JButton btMayBay;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXuatExcel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField intSoGheDB;
    private javax.swing.JTextField intSoGheVIPDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSCB;
    private com.toedter.calendar.JDateChooser tkDate1;
    private com.toedter.calendar.JDateChooser tkDate2;
    private javax.swing.JTextField txtMaChuyen;
    public static javax.swing.JTextField txtMaLoTrinh;
    private javax.swing.JTextField txtMaMB;
    private com.toedter.calendar.JDateChooser txtNgayDen;
    private com.toedter.calendar.JDateChooser txtNgayDi;
    private com.github.lgooddatepicker.components.TimePicker txtTGDen;
    private com.github.lgooddatepicker.components.TimePicker txtTGDi;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
