/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.HoaDonBUS;
import BUS.VeMayBayBUS;
import DTO.HoaDonDTO;
import DTO.VeMayBayDTO;
import static GUI.ChuyenBayGUI.txtMaLoTrinh;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class HoaDonGUI extends javax.swing.JFrame {

    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel model;
    DefaultTableModel model1;
    private String xoaHD;
    String MaHD;

    /**
     * Creates new form HoaDonGUI
     */
    public HoaDonGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSHD = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHD = new javax.swing.JTextField();
        txtNV = new javax.swing.JTextField();
        txtKH = new javax.swing.JTextField();
        btChonKH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgay = new com.toedter.calendar.JDateChooser();
        txtTien = new javax.swing.JTextField();
        txtNote = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVe = new javax.swing.JTable();
        btVE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\NetBeansProjects\\QuanLyBanVeMayBay\\src\\image\\plane.png")); // NOI18N
        jLabel11.setText("QUẢN LÝ BÁN VÉ MÁY BAY");

        jButton1.setText("Trở về");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐẶT VÉ MÁY BAY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách Hàng ", "Ngày Mua", "Tổng tiền", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSHD.setPreferredSize(new java.awt.Dimension(300, 200));
        tblDSHD.setRowHeight(30);
        tblDSHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSHD);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã hóa đơn:");

        jLabel3.setText("Mã Nhân Viên:");

        jLabel4.setText("Mã Khách hàng:");

        txtHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHDKeyTyped(evt);
            }
        });

        txtNV.setEditable(false);

        txtKH.setEditable(false);

        btChonKH.setText("...");
        btChonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonKHActionPerformed(evt);
            }
        });

        jLabel5.setText("Tổng Tiền:");

        jLabel6.setText("Ngày Mua:");

        jLabel7.setText("Ghi Chú:");

        txtNgay.setDateFormatString("yyyy-MM-dd");

        txtTien.setEditable(false);
        txtTien.setText("0");

        jLabel8.setText("VNĐ");

        btAdd.setBackground(java.awt.Color.green);
        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btXoa.setBackground(java.awt.Color.red);
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setBackground(java.awt.Color.cyan);
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btReset.setBackground(java.awt.Color.yellow);
        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết"));

        tblVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Chuyến", "Mã Loại Vé", "Mã Loại Ghế", "Giá"
            }
        ));
        tblVe.setRowHeight(20);
        jScrollPane2.setViewportView(tblVe);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        btVE.setText("Quản lý vé");
        btVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHD)
                            .addComponent(txtNV)
                            .addComponent(txtKH, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtTien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btVE, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNote))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(btVE, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChonKH)
                    .addComponent(jLabel7)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btReset, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(btXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSHDMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSHD.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int i = tblDSHD.getSelectedRow();
        if (i >= 0) {
            HoaDonDTO hoadon = new HoaDonDTO();
            hoadon = HoaDonBUS.dsHoaDon.get(i);
            txtHD.setText(hoadon.getMaHD());
            txtNV.setText(hoadon.getMaNV());
            txtKH.setText(hoadon.getMaKH());
            try {
                txtNgay.setDate(sdf.parse(hoadon.getNgayMua()));
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(HoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            txtTien.setText(String.valueOf(hoadon.getTongTien()));
            txtNote.setText(hoadon.getGhichu());
            //////
            VeMayBayBUS bus = new VeMayBayBUS();
            ArrayList<VeMayBayDTO> list = null;
            try {
                list = bus.timKiem(hoadon.getMaHD());
            } catch (ParseException ex) {
                Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            revalidate();
            Vector header = new Vector();
            header.add("Mã Hóa đơn");
            header.add("Mã Mã chuyến");
            header.add("Mã Mã Loại vé");
            header.add("Mã Loại ghế");
            header.add("Giá");
            model1 = new DefaultTableModel(header, 0);
            for (VeMayBayDTO x : list) {
                Vector row = new Vector();
                row.add(x.getMaVe());
                row.add(x.getMaChuyen());
                row.add(x.getMaLoaiVe());
                row.add(x.getMaLoaiGhe());
                row.add(x.getGia());
                model1.addRow(row);
            }
            tblVe.setModel(model1);
                    VeMayBayBUS busve=new VeMayBayBUS();
            try {
                txtTien.setText(String.valueOf( busve.dtHD(txtHD.getText())));
            } catch (ParseException ex) {
                Logger.getLogger(HoaDonGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblDSHDMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtHD.getText()) || "".equals(txtNV.getText())
                || "".equals(txtKH.getText()) || "".equals(Integer.parseInt(txtTien.getText()))
                || "".equals(txtNV.getText())
                || "".equals(txtNgay.getDate()) || "".equals(txtNote.getText())) {

            JOptionPane.showMessageDialog(null, "Mời bạn nhập đầy đủ thông tin !!!");
        } else {
            int tam = 1;
            HoaDonDTO hd = new HoaDonDTO();
            for (HoaDonDTO x : HoaDonBUS.dsHoaDon) {
                if (x.getMaHD().equals(txtHD.getText())) {
                    tam = 0;
                }
            }
            if (tam == 1) {
                HoaDonBUS bus = new HoaDonBUS();
                HoaDonDTO dto = new HoaDonDTO();
                dto.MaHD = txtHD.getText();
                dto.MaNV = txtNV.getText();
                dto.MaKH = txtKH.getText();
                dto.NgayMua = df.format(txtNgay.getDate());
                dto.TongTien = Integer.parseInt(txtTien.getText());
                dto.Ghichu = txtNote.getText();
                bus.them(dto);
                Vector row = new Vector();
                row.add(dto.MaHD);
                row.add(dto.MaNV);
                row.add(dto.MaKH);
                row.add(dto.NgayMua);
                row.add(dto.TongTien);
                row.add(dto.Ghichu);
                model.addRow(row);
                tblDSHD.setModel(model);
                JOptionPane.showMessageDialog(null, "Bạn đã thêm thành công");
            } else {
                if (tam == 0) {
                    JOptionPane.showMessageDialog(null, "Mã hóa đơn bị trùng mời nhập lại");
                    txtHD.setText(null);
                    txtHD.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSHD.getModel();

        int i = tblDSHD.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để xóa");
        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa hoá đơn", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                HoaDonDTO cb = new HoaDonDTO();
                cb = HoaDonBUS.dsHoaDon.remove(i);
                HoaDonBUS bus = new HoaDonBUS();
                if (i >= 0) {
                    xoaHD = tblDSHD.getValueAt(i, 0).toString();
                }
                bus.xoa(xoaHD);
                model.removeRow(i);
                tblDSHD.setModel(model);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSHD.getModel();
        int i = tblDSHD.getSelectedRow();
        String MaChuyen = txtHD.getText();
        int check = 0;
        for (HoaDonDTO x : HoaDonBUS.dsHoaDon) {
            if (x.getMaHD().equals(txtHD.getText())) {
                check = 1;
            }
        }
        HoaDonBUS.dsHoaDon.stream().filter((x) -> (x.getMaHD().equals(MaChuyen)));
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        } else if (check == 0) {
            JOptionPane.showMessageDialog(null, "Mã hoá đơn không được sửa");
            txtHD.requestFocus();

        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không", "Sửa", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION && check == 1) {

                HoaDonDTO cb = new HoaDonDTO();
                cb.MaHD = txtHD.getText();
                cb.MaNV = txtNV.getText();
                cb.MaKH = txtKH.getText();
                cb.NgayMua = df.format(txtNgay.getDate());
                cb.TongTien = Integer.parseInt(txtTien.getText());
                cb.Ghichu = txtNote.getText();
                HoaDonBUS bus = new HoaDonBUS();
                bus.sua(cb);
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Vector row = new Vector();
                row.add(cb.MaHD);
                row.add(cb.MaNV);
                row.add(cb.MaKH);
                row.add(cb.NgayMua);
                row.add(cb.TongTien);
                row.add(cb.Ghichu);
                model.addRow(row);
                tblDSHD.setModel(model);
                model.setValueAt(cb.MaHD, i, 0);
                model.setValueAt(cb.MaNV, i, 1);
                model.setValueAt(cb.MaKH, i, 2);
                model.setValueAt(cb.NgayMua, i, 3);
                model.setValueAt(cb.TongTien, i, 4);
                model.setValueAt(cb.Ghichu, i, 5);
                bus.docDSHoaDon();
            }
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        txtHD.setText(null);
        txtNV.setText(null);
        txtKH.setText(null);
        txtNgay.setDate(null);
        txtTien.setText(null);
        txtNote.setText(null);
    }//GEN-LAST:event_btResetActionPerformed

    private void btChonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonKHActionPerformed
        // TODO add your handling code here:
        KhachHangGUI dialog = new KhachHangGUI();
        dialog.setVisible(true);
    }//GEN-LAST:event_btChonKHActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        HoaDonBUS bus = new HoaDonBUS();
        if (HoaDonBUS.dsHoaDon == null) {
            bus.docDSHoaDon();
        }
        Vector header = new Vector();
        header.add("Mã Hóa đơn");
        header.add("Mã Nhân Viên");
        header.add("Mã Khách Hàng");
        header.add("Ngày Mua");
        header.add("Tổng tiền");
        header.add("Ghi chú");
        model = new DefaultTableModel(header, 0);
        HoaDonBUS.dsHoaDon.stream().map((lt) -> {
            Vector row = new Vector();
            row.add(lt.MaHD);
            row.add(lt.MaNV);
            row.add(lt.MaKH);
            row.add(lt.NgayMua);

            row.add(lt.TongTien);
            row.add(lt.Ghichu);
            return row;
        }).forEachOrdered((row) -> {
            model.addRow(row);
        });
        tblDSHD.setModel(model);
        /////

    }//GEN-LAST:event_formWindowActivated

    private void btVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVEActionPerformed
        // TODO add your handling code here:
        new VeMayBayGUI().setVisible(true);
                VeMayBayGUI.txtMaVe.setText(txtHD.getText());
    }//GEN-LAST:event_btVEActionPerformed

    private void txtHDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHDKeyTyped
        // TODO add your handling code here:
         VeMayBayBUS busve=new VeMayBayBUS();
            try {
                txtTien.setText(String.valueOf( busve.dtHD(txtHD.getText())));
            } catch (ParseException ex) {
                Logger.getLogger(HoaDonGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_txtHDKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new MenuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btChonKH;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btVE;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDSHD;
    private javax.swing.JTable tblVe;
    public static javax.swing.JTextField txtHD;
    public static javax.swing.JTextField txtKH;
    public static javax.swing.JTextField txtNV;
    private com.toedter.calendar.JDateChooser txtNgay;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtTien;
    // End of variables declaration//GEN-END:variables
}
