/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.LoaiVeBUS;
import DTO.LoaiVeDTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class LoaiVeGUI extends javax.swing.JDialog {

    private DefaultTableModel model;
    private String xoaloaive;
    public String maloaive;

    /**
     * Creates new form LoTrinhGUI
     */
    public LoaiVeGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getContent() {
        return txtMaLoaiVe.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLV = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLoaiVe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        btAddLoaiVe = new javax.swing.JButton();
        btInsertLoaiVe = new javax.swing.JButton();
        btDeleteLoaiVe = new javax.swing.JButton();
        btChonLoaiVe = new javax.swing.JButton();
        btResetLoaiVe = new javax.swing.JButton();
        btCloseLoaiVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOẠI VÉ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tblDSLV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Loại Vé", "Tên Loại", "Giá Tiền"
            }
        ));
        tblDSLV.setRowHeight(30);
        tblDSLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSLVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSLV);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Loại Vé:");

        jLabel6.setText("Giá Tiền:");

        jLabel7.setText("Tên Loại:");

        txtTenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoaiActionPerformed(evt);
            }
        });

        btAddLoaiVe.setText("Thêm");
        btAddLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLoaiVeActionPerformed(evt);
            }
        });

        btInsertLoaiVe.setText("Sửa");
        btInsertLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertLoaiVeActionPerformed(evt);
            }
        });

        btDeleteLoaiVe.setText("Xóa");
        btDeleteLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteLoaiVeActionPerformed(evt);
            }
        });

        btChonLoaiVe.setText("CHỌN");
        btChonLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonLoaiVeActionPerformed(evt);
            }
        });

        btResetLoaiVe.setText("Reset");
        btResetLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetLoaiVeActionPerformed(evt);
            }
        });

        btCloseLoaiVe.setText("THOÁT");
        btCloseLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloseLoaiVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(txtMaLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btAddLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChonLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtGiaTien))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInsertLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btResetLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCloseLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDeleteLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btInsertLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDeleteLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btChonLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btResetLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCloseLoaiVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSLVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSLVMouseClicked
        // TODO add your handling code here:
       DefaultTableModel modelcb = (DefaultTableModel) tblDSLV.getModel();
        int i = tblDSLV.getSelectedRow();
        if (i >= 0) {
            xoaloaive = tblDSLV.getValueAt(i, 0).toString();
            LoaiVeDTO loaive = new LoaiVeDTO();
            loaive = LoaiVeBUS.dsLoaiVe.get(i);
            txtMaLoaiVe.setText(loaive.getMaLoaiVe());
            txtTenLoai.setText(loaive.getTenLoai());
            txtGiaTien.setText(String.valueOf(loaive.getGiaTien()));
            
        }
    }//GEN-LAST:event_tblDSLVMouseClicked

    private void btResetLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetLoaiVeActionPerformed
        // TODO add your handling code here:
        txtMaLoaiVe.setText("");
         txtTenLoai.setText("");
        txtGiaTien.setText("");
    }//GEN-LAST:event_btResetLoaiVeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        LoaiVeBUS bus = new LoaiVeBUS();
        if (LoaiVeBUS.dsLoaiVe == null) {
            bus.docDSLoaiVe();
        }
        Vector header = new Vector();
        header.add("Mã Loại Vé");
        header.add("Tên Loại");
        header.add("Giá Tiền");
        model = new DefaultTableModel(header, 0);
        for (LoaiVeDTO lv : LoaiVeBUS.dsLoaiVe) {
            Vector row = new Vector();
            row.add(lv.MaLoaiVe);
            row.add(lv.TenLoai);
            row.add(lv.GiaTien);
            model.addRow(row);
        }
        tblDSLV.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    private void txtTenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiActionPerformed

    private void btAddLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLoaiVeActionPerformed
        // TODO add your handling code here:
        LoaiVeDTO lv = new LoaiVeDTO();
        lv.MaLoaiVe = txtMaLoaiVe.getText();
        lv.TenLoai = txtTenLoai.getText();
        lv.GiaTien = Integer.parseInt(txtGiaTien.getText());
        LoaiVeBUS bus = new LoaiVeBUS();
        bus.them(lv);
        Vector row = new Vector();
        row.add(lv.MaLoaiVe);
        row.add(lv.TenLoai);
        row.add(lv.GiaTien);
        model.addRow(row);
        tblDSLV.setModel(model);
    }//GEN-LAST:event_btAddLoaiVeActionPerformed

    private void btInsertLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertLoaiVeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSLV.getModel();
        int i = tblDSLV.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        }
        LoaiVeDTO lv = new LoaiVeDTO();
        lv.MaLoaiVe = txtMaLoaiVe.getText();
        lv.TenLoai = txtTenLoai.getText();
        lv.GiaTien =  Integer.parseInt(txtGiaTien.getText());
        LoaiVeBUS bus = new LoaiVeBUS();
        bus.sua(lv);
        
        tblDSLV.setModel(model);
        model.setValueAt(lv.MaLoaiVe, i, 0);
        model.setValueAt(lv.TenLoai, i, 1);
        model.setValueAt(lv.GiaTien, i, 2);
        bus.docDSLoaiVe();
    }//GEN-LAST:event_btInsertLoaiVeActionPerformed

    private void btDeleteLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteLoaiVeActionPerformed
        // TODO add your handling code here:
         DefaultTableModel modelcb = (DefaultTableModel) tblDSLV.getModel();

        int i = tblDSLV.getSelectedRow();
                if(i<0)
                 {
                     JOptionPane.showMessageDialog(null,"Bạn cần chọn dòng để xóa");
                 }
                else{
                      int chon = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không","Xóa sách",JOptionPane.YES_NO_OPTION);
                      if(chon == JOptionPane.YES_OPTION){
                            LoaiVeDTO lv = new LoaiVeDTO();
                            lv = LoaiVeBUS.dsLoaiVe.remove(i);
                            LoaiVeBUS bus = new LoaiVeBUS();
                            if (i >= 0) {
                            xoaloaive = tblDSLV.getValueAt(i, 0).toString();
                            }
                            bus.xoa(xoaloaive);
                            model.removeRow(i);
                            tblDSLV.setModel(model);
                      }
                }
    }//GEN-LAST:event_btDeleteLoaiVeActionPerformed

    private void btChonLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonLoaiVeActionPerformed
        // TODO add your handling code here:
        int i = tblDSLV.getSelectedRow();
            if(i>=0)
            {
                LoaiVeDTO lv = new LoaiVeDTO();
                LoaiVeBUS bus = new LoaiVeBUS();
                if(LoaiVeBUS.dsLoaiVe == null) bus.docDSLoaiVe();
                lv = bus.dsLoaiVe.get(i);
                maloaive = lv.getMaLoaiVe();
                VeMayBayGUI.txtMaLoaiVe.setText(maloaive);
                VeMayBayGUI.txtMaLoaiVe.setEditable(false);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng trên bảng");
            }
    }//GEN-LAST:event_btChonLoaiVeActionPerformed

    private void btCloseLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloseLoaiVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCloseLoaiVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiVeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiVeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiVeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiVeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoaiVeGUI dialog = new LoaiVeGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLoaiVe;
    private javax.swing.JButton btChonLoaiVe;
    private javax.swing.JButton btCloseLoaiVe;
    private javax.swing.JButton btDeleteLoaiVe;
    private javax.swing.JButton btInsertLoaiVe;
    private javax.swing.JButton btResetLoaiVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSLV;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaLoaiVe;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
    

}
