/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.LoTrinhBUS;
import DTO.LoTrinhDTO;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class LoTrinhGUI extends javax.swing.JDialog {

    private DefaultTableModel model;
    public  String MaLoai;

    /**
     * Creates new form LoTrinhGUI
     */
    public LoTrinhGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public String getContent() {
        return txtMaLoTrinh.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSLT = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaLoTrinh = new javax.swing.JTextField();
        intTG1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNoiDi = new javax.swing.JTextField();
        txtNoiDen = new javax.swing.JTextField();
        btAddLT = new javax.swing.JButton();
        btEditLT = new javax.swing.JButton();
        btXoaLT = new javax.swing.JButton();
        btChonLT = new javax.swing.JButton();
        btResetLT = new javax.swing.JButton();
        btExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 240));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LỘ TRÌNH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        tblDSLT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Lộ Trình", "Nơi Đi", "Nơi Đến", "Thời Gian Bay"
            }
        ));
        tblDSLT.setRowHeight(30);
        tblDSLT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSLTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSLT);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Lộ Trình:");

        jLabel3.setText("Thời Gian Bay:");

        jLabel4.setText("Giờ");

        jLabel6.setText("Nơi Đến:");

        jLabel7.setText("Nơi Đi:");

        btAddLT.setText("Thêm");
        btAddLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddLTActionPerformed(evt);
            }
        });

        btEditLT.setText("Sửa");
        btEditLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditLTActionPerformed(evt);
            }
        });

        btXoaLT.setText("Xóa");
        btXoaLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaLTActionPerformed(evt);
            }
        });

        btChonLT.setText("CHỌN");
        btChonLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonLTActionPerformed(evt);
            }
        });

        btResetLT.setText("Reset");
        btResetLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetLTActionPerformed(evt);
            }
        });

        btExit.setText("THOÁT");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intTG1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(txtMaLoTrinh)))
                    .addComponent(btAddLT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChonLT, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNoiDi, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(txtNoiDen))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEditLT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btResetLT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btXoaLT, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaLoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intTG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAddLT, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btEditLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btXoaLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btChonLT, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(btResetLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDSLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSLTMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modellt = (DefaultTableModel) tblDSLT.getModel();
        int i = tblDSLT.getSelectedRow();
        if (i >= 0) {
            txtMaLoTrinh.setText(tblDSLT.getValueAt(i, 0).toString());
        }
    }//GEN-LAST:event_tblDSLTMouseClicked

    private void btResetLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetLTActionPerformed
        // TODO add your handling code here:
        txtMaLoTrinh.setText(null);
        txtNoiDi.setText(null);
        txtNoiDen.setText(null);
        intTG1.setText(null);

    }//GEN-LAST:event_btResetLTActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        LoTrinhBUS bus = new LoTrinhBUS();
        if (LoTrinhBUS.dslt == null) {
            bus.docDSLT();
        }
        Vector header = new Vector();
        header.add("Mã Lộ Trình");
        header.add("Nơi Đi");
        header.add("Nơi Đến");
        header.add("Thời Gian Bay");
        model = new DefaultTableModel(header, 0);
        LoTrinhBUS.dslt.stream().map((lt) -> {
            Vector row = new Vector();
            row.add(lt.MaLoTrinh);
            row.add(lt.NoiDi);
            row.add(lt.NoiDen);
            row.add(lt.TGBay);
            return row;
        }).forEachOrdered((row) -> {
            model.addRow(row);
        });
        tblDSLT.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    private void btAddLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddLTActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtMaLoTrinh.getText()) || "".equals(txtNoiDi.getText())
                || "".equals(txtNoiDen.getText()) || "".equals(Integer.parseInt(intTG1.getText()))) {

            JOptionPane.showMessageDialog(null, "Mời bạn nhập đầy đủ thông tin !!!");
        } else {
            LoTrinhBUS bus = new LoTrinhBUS();
            LoTrinhDTO dto = new LoTrinhDTO();
            dto.MaLoTrinh = txtMaLoTrinh.getText();
            dto.NoiDi = txtNoiDi.getText();
            dto.NoiDen = txtNoiDen.getText();
            dto.TGBay = Integer.parseInt(intTG1.getText());
            bus.them(dto);
            Vector row = new Vector();
            row.add(dto.MaLoTrinh);
            row.add(dto.NoiDi);
            row.add(dto.NoiDen);
            row.add(dto.TGBay);
            model.addRow(row);
            tblDSLT.setModel(model);
        }
    }//GEN-LAST:event_btAddLTActionPerformed

    private void btEditLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditLTActionPerformed
        // TODO add your handling code here:
        int i = tblDSLT.getSelectedRow();
        String MaLoTrinh = txtMaLoTrinh.getText();
        int check = 0;
        for (LoTrinhDTO x : LoTrinhBUS.dslt) {
            if (x.getMaLoTrinh().equals(txtMaLoTrinh.getText())) {
                check = 1;
            }
        }
        LoTrinhBUS.dslt.stream().filter((x) -> (x.getMaLoTrinh().equals(MaLoTrinh)));
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        } else if (check == 0) {
            JOptionPane.showMessageDialog(null, "Mã lộ trình không được sửa");
            txtMaLoTrinh.requestFocus();

        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không", "Sửa", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION && check == 1) {
                LoTrinhDTO lotrinh = new LoTrinhDTO();
                lotrinh = LoTrinhBUS.dslt.set(i, lotrinh);
                lotrinh.NoiDi = txtNoiDi.getText();
                lotrinh.NoiDen = txtNoiDen.getText();
                lotrinh.TGBay = Integer.parseInt(intTG1.getText());
                LoTrinhBUS bus = new LoTrinhBUS();
                bus.sua(lotrinh);
                model.setValueAt(lotrinh.MaLoTrinh, i, 0);
                model.setValueAt(lotrinh.NoiDi, i, 1);
                model.setValueAt(lotrinh.NoiDen, i, 2);
                model.setValueAt(lotrinh.TGBay, i, 3);
                bus.docDSLT();
            }

        }

    }//GEN-LAST:event_btEditLTActionPerformed

    private void btXoaLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaLTActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSLT.getModel();

        int i = tblDSLT.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để xóa");
        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa lo trinh", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                LoTrinhDTO lt = new LoTrinhDTO();
                lt = LoTrinhBUS.dslt.remove(i);
                LoTrinhBUS bus = new LoTrinhBUS();
                if (i >= 0) {
                    bus.xoa(tblDSLT.getValueAt(i, 0).toString());
                }

                model.removeRow(i);
                tblDSLT.setModel(model);
            }
        }
    }//GEN-LAST:event_btXoaLTActionPerformed

    private void btChonLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonLTActionPerformed
        // TODO add your handling code here:
 int i = tblDSLT.getSelectedRow();
            if(i>=0)
            {
                LoTrinhDTO lt = new LoTrinhDTO();
                LoTrinhBUS bus = new LoTrinhBUS();
                if(LoTrinhBUS.dslt == null) bus.docDSLT();
                lt = bus.dslt.get(i);
                MaLoai = lt.getMaLoTrinh();
                ChuyenBayGUI.txtMaLoTrinh.setText(MaLoai);
                ChuyenBayGUI.txtMaLoTrinh.setEditable(false);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng trên bảng");
            }
    }//GEN-LAST:event_btChonLTActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoTrinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoTrinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoTrinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoTrinhGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoTrinhGUI dialog = new LoTrinhGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddLT;
    private javax.swing.JButton btChonLT;
    private javax.swing.JButton btEditLT;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btResetLT;
    private javax.swing.JButton btXoaLT;
    private javax.swing.JTextField intTG1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSLT;
    private javax.swing.JTextField txtMaLoTrinh;
    private javax.swing.JTextField txtNoiDen;
    private javax.swing.JTextField txtNoiDi;
    // End of variables declaration//GEN-END:variables
}
