/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.ChuyenBayBUS;
import BUS.VeMayBayBUS;
import DTO.ChuyenBayDTO;
import DTO.VeMayBayDTO;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class VeMayBayGUI extends javax.swing.JFrame {


    private DefaultTableModel model;
    private String xoaVMB;

    /**
     * Creates new form ChuyenBayGUI
     */
    public VeMayBayGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaLoaiGhe = new javax.swing.JTextField();
        txtMaChuyen = new javax.swing.JTextField();
        txtMaLoaiVe = new javax.swing.JTextField();
        btMaLoaiGhe = new javax.swing.JButton();
        btMaLoaiVe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btAddChuyenBay = new javax.swing.JButton();
        btInsertVeMayBay = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btTimKiemVeMayBay = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtGiaBD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGiaKT = new javax.swing.JTextField();
        btTimKiemNC = new javax.swing.JButton();
        btDeleteVeMayBay = new javax.swing.JButton();
        txtMaVe = new javax.swing.JTextField();
        btmachuyen = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSVe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUẢN LÝ BÁN VÉ MÁY BAY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ VÉ MÁY BAY");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Mã Loại Ghế:");

        jLabel3.setText("Mã Chuyến:");

        jLabel4.setText("Mã Loại Vé:");

        txtMaLoaiGhe.setEditable(false);

        txtMaChuyen.setEditable(false);
        txtMaChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaChuyenActionPerformed(evt);
            }
        });

        txtMaLoaiVe.setEditable(false);

        btMaLoaiGhe.setText("...");
        btMaLoaiGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaLoaiGheActionPerformed(evt);
            }
        });

        btMaLoaiVe.setText("...");
        btMaLoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaLoaiVeActionPerformed(evt);
            }
        });

        jLabel5.setText("Mã Hóa Đơn:");

        jLabel9.setText("Giá:");

        btAddChuyenBay.setBackground(new java.awt.Color(0, 255, 0));
        btAddChuyenBay.setText("Thêm");
        btAddChuyenBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddChuyenBayMouseClicked(evt);
            }
        });

        btInsertVeMayBay.setBackground(new java.awt.Color(0, 255, 255));
        btInsertVeMayBay.setText("Sửa");
        btInsertVeMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertVeMayBayActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(240, 252, 0));
        btReset.setText("Reset");
        btReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btResetMouseClicked(evt);
            }
        });

        btTimKiemVeMayBay.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm Kiếm"));

        jLabel7.setText("Giá từ:");

        txtGiaBD.setText("1000000");

        jLabel8.setText("đến");

        txtGiaKT.setText("5000000");

        btTimKiemNC.setText("Tìm kiếm");
        btTimKiemNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemNCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btTimKiemVeMayBayLayout = new javax.swing.GroupLayout(btTimKiemVeMayBay);
        btTimKiemVeMayBay.setLayout(btTimKiemVeMayBayLayout);
        btTimKiemVeMayBayLayout.setHorizontalGroup(
            btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btTimKiemVeMayBayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btTimKiemVeMayBayLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiaBD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btTimKiemVeMayBayLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btTimKiemNC)
                            .addComponent(txtGiaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        btTimKiemVeMayBayLayout.setVerticalGroup(
            btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btTimKiemVeMayBayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGiaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btTimKiemVeMayBayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTimKiemNC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btDeleteVeMayBay.setBackground(new java.awt.Color(255, 0, 0));
        btDeleteVeMayBay.setText("Xóa");
        btDeleteVeMayBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeleteVeMayBayMouseClicked(evt);
            }
        });
        btDeleteVeMayBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteVeMayBayActionPerformed(evt);
            }
        });

        txtMaVe.setEditable(false);
        txtMaVe.setText("null");

        btmachuyen.setText("...");
        btmachuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmachuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMaLoaiVe, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(txtMaChuyen, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLoaiGhe, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btMaLoaiGhe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btMaLoaiVe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btmachuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(321, 321, 321))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btAddChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btDeleteVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btInsertVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(btTimKiemVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btmachuyen))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtMaLoaiGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btMaLoaiGhe)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btMaLoaiVe)
                        .addComponent(txtMaLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAddChuyenBay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInsertVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btDeleteVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btTimKiemVeMayBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblDSVe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Vé", "Mã Chuyến", "Mã Loại  Vé", "Mã Loại Ghế", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSVe.setPreferredSize(new java.awt.Dimension(300, 200));
        tblDSVe.setRowHeight(30);
        tblDSVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSVeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSVe);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        VeMayBayBUS bus = new VeMayBayBUS();
        if (VeMayBayBUS.dsVeMayBay == null) {
            bus.docDSVeMayBay();
        }
        Vector header = new Vector();
        header.add("Mã Vé ");
        header.add("Mã Chuyến");
        header.add("Mã Loại Vé");
        header.add("Mã Loại Ghế");
        header.add("Giá");
       
        model = new DefaultTableModel(header, 0);
        for (VeMayBayDTO vmb : VeMayBayBUS.dsVeMayBay) {
            Vector row = new Vector();
            row.add(vmb.MaVe);
            row.add(vmb.MaChuyen);
            row.add(vmb.MaLoaiVe);
            row.add(vmb.MaLoaiGhe);
            row.add(vmb.Gia);
            model.addRow(row);
        }
        tblDSVe.setModel(model);

    }//GEN-LAST:event_formWindowActivated

    private void btAddChuyenBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddChuyenBayMouseClicked
        // TODO add your handling code here:
        VeMayBayDTO vmb = new VeMayBayDTO();
        vmb.MaVe = txtMaVe.getText();
        vmb.MaChuyen = txtMaChuyen.getText();
        vmb.MaLoaiVe = txtMaLoaiVe.getText();
        vmb.MaLoaiGhe = txtMaLoaiGhe.getText();
        vmb.Gia = Integer.parseInt(txtGia.getText());
        VeMayBayBUS bus = new VeMayBayBUS();
        bus.them(vmb);
        ChuyenBayBUS buscb=new ChuyenBayBUS();
    
        Vector row = new Vector();
        row.add(vmb.MaVe);
        row.add(vmb.MaChuyen);
        row.add(vmb.MaLoaiVe);
        row.add(vmb.MaLoaiGhe);
        row.add(vmb.Gia);
        model.addRow(row);
        tblDSVe.setModel(model);
    }//GEN-LAST:event_btAddChuyenBayMouseClicked

    private void btMaLoaiGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaLoaiGheActionPerformed
        // TODO add your handling code here:
        ChiTietLoaiGheGUI dialog = new ChiTietLoaiGheGUI(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
        txtMaLoaiGhe.setText(temp);
    }//GEN-LAST:event_btMaLoaiGheActionPerformed

    private void btMaLoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaLoaiVeActionPerformed
        // TODO add your handling code here:
        LoaiVeGUI dialog = new LoaiVeGUI(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
        txtMaLoaiVe.setText(temp);
    }//GEN-LAST:event_btMaLoaiVeActionPerformed

    private void tblDSVeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSVeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSVe.getModel();
        int i = tblDSVe.getSelectedRow();
        if (i >= 0) {
            xoaVMB = tblDSVe.getValueAt(i, 0).toString();
            VeMayBayDTO vemaybay = new VeMayBayDTO();
            vemaybay = VeMayBayBUS.dsVeMayBay.get(i);
            txtMaVe.setText(vemaybay.getMaVe());
            txtMaChuyen.setText(vemaybay.getMaChuyen());
            txtMaLoaiVe.setText(vemaybay.getMaLoaiVe());
            txtMaLoaiGhe.setText(vemaybay.getMaLoaiGhe());
            txtGia.setText(String.valueOf(vemaybay.getGia()));
            
        }
    }//GEN-LAST:event_tblDSVeMouseClicked

    private void btDeleteVeMayBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteVeMayBayMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSVe.getModel();

        int i = tblDSVe.getSelectedRow();
                if(i<0)
                 {
                   JOptionPane.showMessageDialog(null,"Bạn cần chọn dòng để xóa");
                 }
                else{
                      int chon = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không","Xóa sách",JOptionPane.YES_NO_OPTION);
                      if(chon == JOptionPane.YES_OPTION){
                            VeMayBayDTO vmb = new VeMayBayDTO();
                            vmb = VeMayBayBUS.dsVeMayBay.remove(i);
                            VeMayBayBUS bus = new VeMayBayBUS();
                            if (i >= 0) {
                            xoaVMB = tblDSVe.getValueAt(i, 0).toString();
                            }
                            bus.xoa(xoaVMB);
                            model.removeRow(i);
                            tblDSVe.setModel(model);
                      }
                }
    }//GEN-LAST:event_btDeleteVeMayBayMouseClicked

    private void btResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btResetMouseClicked
        // TODO add your handling code here:
        txtMaVe.setText("");
         txtMaChuyen.setText("");
        txtMaLoaiGhe.setText("");
        txtMaLoaiVe.setText("");
        txtGia.setText("");
        
        
    }//GEN-LAST:event_btResetMouseClicked

    private void btInsertVeMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertVeMayBayActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelcb = (DefaultTableModel) tblDSVe.getModel();
        int i = tblDSVe.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để sửa");
        }
        VeMayBayDTO vmb = new VeMayBayDTO();
        vmb.MaVe = txtMaVe.getText();
        vmb.MaChuyen = txtMaChuyen.getText();
        vmb.MaLoaiVe = txtMaLoaiVe.getText();
        vmb.MaLoaiGhe = txtMaLoaiGhe.getText();
        vmb.Gia =  Integer.parseInt(txtGia.getText());
        VeMayBayBUS bus = new VeMayBayBUS();
        bus.sua(vmb);
        
        tblDSVe.setModel(model);
        model.setValueAt(vmb.MaVe, i, 0);
        model.setValueAt(vmb.MaChuyen, i, 1);
        model.setValueAt(vmb.MaLoaiVe, i, 2);
        model.setValueAt(vmb.MaLoaiGhe, i, 3);
        model.setValueAt(vmb.Gia, i, 4);
        bus.docDSVeMayBay();
    }//GEN-LAST:event_btInsertVeMayBayActionPerformed

    private void btDeleteVeMayBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteVeMayBayActionPerformed
        // TODO add your handling code here:
         DefaultTableModel modelcb = (DefaultTableModel) tblDSVe.getModel();

        int i = tblDSVe.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(null, "Bạn cần chọn dòng để xóa");
        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không", "Xóa vé", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                VeMayBayDTO vmb = new VeMayBayDTO();
                vmb = VeMayBayBUS.dsVeMayBay.remove(i);
                VeMayBayBUS bus = new VeMayBayBUS();
                if (i >= 0) {
                    xoaVMB = tblDSVe.getValueAt(i, 0).toString();
                }
                bus.xoa(xoaVMB);
                model.removeRow(i);
                tblDSVe.setModel(model);
            }
        }
    }//GEN-LAST:event_btDeleteVeMayBayActionPerformed

    private void btTimKiemNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemNCActionPerformed
        // TODO add your handling code here:                                           
        // TODO add your handling code here:
       VeMayBayBUS bus=new VeMayBayBUS();
        ArrayList<VeMayBayDTO> list = null;
        try {
            list = bus.timkiemNC(Integer.parseInt(txtGiaBD.getText()), Integer.parseInt(txtGiaKT.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(ChuyenBayGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
                revalidate();
                for(VeMayBayDTO i : list){
                    Vector row = new Vector();
                    row.add(i.getMaVe());
                    row.add(i.getMaChuyen());
                    row.add(i.getMaLoaiVe());
                    row.add(i.getMaLoaiGhe());
                    row.add(i.getGia());
                    model.addRow(row);
                }
    
    }//GEN-LAST:event_btTimKiemNCActionPerformed

    private void txtMaChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaChuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaChuyenActionPerformed

    private void btmachuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmachuyenActionPerformed
        // TODO add your handling code here:
      ChuyenBayV2GUI1 dialog = new ChuyenBayV2GUI1(this, rootPaneCheckingEnabled);
        dialog.setVisible(true);
        String temp = dialog.getContent();
        txtMaChuyen.setText(temp);
    }//GEN-LAST:event_btmachuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeMayBayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeMayBayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeMayBayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeMayBayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeMayBayGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddChuyenBay;
    private javax.swing.JButton btDeleteVeMayBay;
    private javax.swing.JButton btInsertVeMayBay;
    private javax.swing.JButton btMaLoaiGhe;
    private javax.swing.JButton btMaLoaiVe;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTimKiemNC;
    private javax.swing.JPanel btTimKiemVeMayBay;
    private javax.swing.JButton btmachuyen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDSVe;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtGiaBD;
    private javax.swing.JTextField txtGiaKT;
    public static javax.swing.JTextField txtMaChuyen;
    public static javax.swing.JTextField txtMaLoaiGhe;
    public static javax.swing.JTextField txtMaLoaiVe;
    public static javax.swing.JTextField txtMaVe;
    // End of variables declaration//GEN-END:variables

    
}
